### ISSUE TITLE
Move firmware compilation and programming into the SDK

### ISSUE THREAD

**Issue by willz1200** [willz1200/Hexa-Driver#20]
It would be useful if firmware could be compiled/debugged from within the SDK. Therefore a tab should be added which interfaces with arduino CLI

**Comment by russellgrim** [comment]
This should be its own file. something like "firmware downloader" which you can call from the GUI code.

**Comment by willz1200** [comment]
programming layout add to the GUI with commit: 38cce607e798a7423dad690b37d05f375e46a74b

**Comment by willz1200** [comment]
Feature added with commit: bb4f985e2aebe703b8372da7c1e01b5b41a26a4b

**Comment by willz1200** [comment]
merged to develop branch with #23
